---
abstract: 'Check if you are currently in compile time or run time'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Phase
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  Test::Spec: '0'
resources:
  X_keywords:
    - perl
    - global
    - phase
  bugtracker: https://github.com/drmuey/p5-Perl-Phase/issues
  repository: https://github.com/drmuey/p5-Perl-Phase.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
